### ISSUE TITLE
定时发送消息失败

### ISSUE THREAD

**Issue by kendajiwaimai** [PerfBleu/everyday_news#1]
报错信息：
![1111](https://user-images.githubusercontent.com/42399023/170849247-d8e2b4ed-e832-4f15-9b53-0aaf0c991259.png)

**Comment by PerfBleu** [comment]
我这边试了一下，正常的，你试试更新一下，我以前broadcast写的不对，传进了bot和ev

**Comment by kendajiwaimai** [comment]
更新之后OK了😆
