### ISSUE TITLE
今日（20220618）无法获取图片Url

### ISSUE THREAD

**Issue by FLAG250** [PerfBleu/everyday_news#2]
目前无法获取Url
直接访问
http://api.soyiji.com//news_jpg
返回
{"message":"Requests rate limited. stage:trafficcontrol"}

我暂时用了
https://api.iyk0.com/60s/
代替

修改如下
def getPicUrl():
    getObject = req.get('https://api.iyk0.com/60s/') #原getObject = req.get('http://api.soyiji.com//news_jpg')

    if getObject.status_code != 200:
        sv.logger.warning('URL获取失败')
        return()
    else:
        sv.logger.info('图片URL获取成功')
    return(json.loads(getObject.text)['imageUrl']) #原return(json.loads(getObject.text)['url'])

>>>
def getImg():
>>>
    getObject = req.get(url=getPicUrl())

虽然还是原来的
http://api.soyiji.com//news_jpg
看起来好点
希望能有其他替换的api

**Comment by PerfBleu** [comment]
联系了易即今日开发者，api维护中，开放时间待定

**Comment by PerfBleu** [comment]
api已修复
